## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
ords_prods_merge = pd.read_pickle(r"C:\Users\Windows\Instacart Basket Analysis\02 Data\Prepared Data\ords_prods_merge1.pkl")

In [3]:
ords_prods_merge.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,busiest_days,busiest_period_of_day,price_range_loc
0,1,Chocolate Sandwich Cookies,19,19,5.8,3139998,138,28,6,11,3.0,5,0,Regularly busy,Most orders,Mid-range product
1,1,Chocolate Sandwich Cookies,19,19,5.8,1977647,138,30,6,17,20.0,1,1,Regularly busy,Most orders,Mid-range product
2,1,Chocolate Sandwich Cookies,19,19,5.8,389851,709,2,0,21,6.0,20,0,Busiest day,Average orders,Mid-range product
3,1,Chocolate Sandwich Cookies,19,19,5.8,652770,764,1,3,13,7.0,10,0,Slowest day,Most orders,Mid-range product
4,1,Chocolate Sandwich Cookies,19,19,5.8,1813452,764,3,4,17,9.0,11,1,Slowest day,Most orders,Mid-range product
5,1,Chocolate Sandwich Cookies,19,19,5.8,1701441,777,16,1,7,26.0,7,0,Busiest day,Average orders,Mid-range product
6,1,Chocolate Sandwich Cookies,19,19,5.8,1871483,825,3,2,14,30.0,2,0,Regularly busy,Most orders,Mid-range product
7,1,Chocolate Sandwich Cookies,19,19,5.8,1290456,910,12,3,10,30.0,1,0,Slowest day,Most orders,Mid-range product
8,1,Chocolate Sandwich Cookies,19,19,5.8,369558,1052,10,1,20,19.0,1,0,Busiest day,Average orders,Mid-range product
9,1,Chocolate Sandwich Cookies,19,19,5.8,589712,1052,15,1,12,15.0,2,1,Busiest day,Most orders,Mid-range product

## Task 4.8 Code Along

In [4]:
# create a subset
df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 16)

In [6]:
df.groupby('product_name')

In [7]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [8]:
df.groupby('department_id')['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

In [9]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.447411   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.803851   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

In [10]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order
0,1,Chocolate Sandwich Cookies,19,19,5.8,3139998,138,28,6,11,3.0,5,0,Regularly busy,Most orders,Mid-range product,32
1,1,Chocolate Sandwich Cookies,19,19,5.8,1977647,138,30,6,17,20.0,1,1,Regularly busy,Most orders,Mid-range product,32
2,1,Chocolate Sandwich Cookies,19,19,5.8,389851,709,2,0,21,6.0,20,0,Busiest day,Average orders,Mid-range product,5
3,1,Chocolate Sandwich Cookies,19,19,5.8,652770,764,1,3,13,7.0,10,0,Slowest day,Most orders,Mid-range product,3
4,1,Chocolate Sandwich Cookies,19,19,5.8,1813452,764,3,4,17,9.0,11,1,Slowest day,Most orders,Mid-range product,3
5,1,Chocolate Sandwich Cookies,19,19,5.8,1701441,777,16,1,7,26.0,7,0,Busiest day,Average orders,Mid-range product,26
6,1,Chocolate Sandwich Cookies,19,19,5.8,1871483,825,3,2,14,30.0,2,0,Regularly busy,Most orders,Mid-range product,9
7,1,Chocolate Sandwich Cookies,19,19,5.8,1290456,910,12,3,10,30.0,1,0,Slowest day,Most orders,Mid-range product,12
8,1,Chocolate Sandwich Cookies,19,19,5.8,369558,1052,10,1,20,19.0,1,0,Busiest day,Average orders,Mid-range product,20
9,1,Chocolate Sandwich Cookies,19,19,5.8,589712,1052,15,1,12,15.0,2,1,Busiest day,Most orders,Mid-range product,20
10,1,Chocolate Sandwich Cookies,19,19,5.8,1798115,1379,1,5,11,7.0,1,0,Regularly busy,Most orders,Mid-range product,10
11,1,Chocolate Sandwich Cookies,19,19,5.8,497193,1480,36,3,13,7.0,1,0,Slowest day,Most orders,Mid-range product,43
12,1,Chocolate Sandwich Cookies,19,19,5.8,1727826,1480,38,4,13,7.0,3,1,Slowest day,Most orders,Mid-range product,43
13,1,Chocolate Sandwich Cookies,19,19,5.8,2694698,1480,39,2,12,12.0,4,1,Regularly busy,Most orders,Mid-range product,43
14,1,Chocolate Sandwich Cookies,19,19,5.8,3171753,1494,6,3,10,2.0,8,0,Slowest day,Most orders,Mid-range product,13

In [14]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [15]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [16]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [17]:
ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [20]:
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 18 columns):
 #   Column                  Dtype
---  ------                  -----
 0   product_id              int32
 1   product_name            category
 2   aisle_id                int16
 3   department_id           int8
 4   prices                  float64
 5   order_id                int32
 6   user_id                 int32
 7   order_number            int8
 8   orders_day_of_week      int8
 9   hour_of_day_ordered     int8
 10  days_since_prior_order  float16
 11  add_to_cart_order       int16
 12  reordered               int8
 13  busiest_days            category
 14  busiest_period_of_day   category
 15  price_range_loc         category
 16  max_order               int8
 17  loyalty_flag            object
dtypes: category(4), float16(1), float64(1), int16(2), int32(3), int8(6), object(1)
memory usage: 1.7+ GB

In [21]:
ords_prods_merge['loyalty_flag'] = ords_prods_merge['loyalty_flag'].astype('category')

In [22]:
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 18 columns):
 #   Column                  Dtype
---  ------                  -----
 0   product_id              int32
 1   product_name            category
 2   aisle_id                int16
 3   department_id           int8
 4   prices                  float64
 5   order_id                int32
 6   user_id                 int32
 7   order_number            int8
 8   orders_day_of_week      int8
 9   hour_of_day_ordered     int8
 10  days_since_prior_order  float16
 11  add_to_cart_order       int16
 12  reordered               int8
 13  busiest_days            category
 14  busiest_period_of_day   category
 15  price_range_loc         category
 16  max_order               int8
 17  loyalty_flag            category
dtypes: category(5), float16(1), float64(1), int16(2), int32(3), int8(6)
memory usage: 1.4 GB

In [25]:
ords_prods_merge[['user_id', 'loyalty_flag', 'max_order']].head(60)

    user_id      loyalty_flag  max_order
0       138  Regular customer         32
1       138  Regular customer         32
2       709      New customer          5
3       764      New customer          3
4       764      New customer          3
5       777  Regular customer         26
6       825      New customer          9
7       910  Regular customer         12
8      1052  Regular customer         20
9      1052  Regular customer         20
10     1379      New customer         10
11     1480    Loyal customer         43
12     1480    Loyal customer         43
13     1480    Loyal customer         43
14     1494  Regular customer         13
15     1494  Regular customer         13
16     1494  Regular customer         13
17     1540  Regular customer         28
18     1540  Regular customer         28
19     1540  Regular customer         28
20     1540  Regular customer         28
21     1540  Regular customer         28
22     1540  Regular customer         28
23     1540  Regular customer         28
24     1540  Regular customer         28
25     1540  Regular customer         28
26     1540  Regular customer         28
27     1540  Regular customer         28
28     1540  Regular customer         28
29     1540  Regular customer         28
30     1540  Regular customer         28
31     1540  Regular customer         28
32     1540  Regular customer         28
33     1540  Regular customer         28
34     1598      New customer          4
35     1598      New customer          4
36     1598      New customer          4
37     1647      New customer         10
38     1647      New customer         10
39     1647      New customer         10
40     1647      New customer         10
41     1647      New customer         10
42     2833      New customer         10
43     2850  Regular customer         23
44     2857  Regular customer         25
45     3010  Regular customer         13
46     3029      New customer          5
47     3395      New customer          6
48     3904      New customer          3
49     4006    Loyal customer         42
50     4006    Loyal customer         42
51     4006    Loyal customer         42
52     4006    Loyal customer         42
53     4006    Loyal customer         42
54     4122  Regular customer         40
55     4141      New customer          9
56     4343      New customer          4
57     4553      New customer          4
58     4845  Regular customer         14
59     6866      New customer          6

## Task 4.8 begins

### step 1- see above

In [27]:
# checking columns 
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,19,19,5.8,3139998,138,28,6,11,3.0,5,0,Regularly busy,Most orders,Mid-range product,32,Regular customer
1,1,Chocolate Sandwich Cookies,19,19,5.8,1977647,138,30,6,17,20.0,1,1,Regularly busy,Most orders,Mid-range product,32,Regular customer
2,1,Chocolate Sandwich Cookies,19,19,5.8,389851,709,2,0,21,6.0,20,0,Busiest day,Average orders,Mid-range product,5,New customer
3,1,Chocolate Sandwich Cookies,19,19,5.8,652770,764,1,3,13,7.0,10,0,Slowest day,Most orders,Mid-range product,3,New customer
4,1,Chocolate Sandwich Cookies,19,19,5.8,1813452,764,3,4,17,9.0,11,1,Slowest day,Most orders,Mid-range product,3,New customer

### Step 2

In [28]:
# Group by department_id, find the mean value of order_numbers per user_id / customer

#department_id from the subset
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Step 3 

##### The results of the entire dataframe vary from results of the subset, but within a narrow margin.

### Step 4


##### see above  - already completed in the Code Along

### Step 5

In [32]:
# Group by loyalty_flag to find average of prices paid ine ach category 
ords_prods_merge.groupby('loyalty_flag').agg({'prices':['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

#### The prices of products purchased by loyal customers are lower than those purchaed by either new or regular customers.

### Step 6

In [33]:
# find the mean of prices paid by each user_id 

ords_prods_merge['avg_spending'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [34]:
ords_prods_merge.head(5)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_spending
0,1,Chocolate Sandwich Cookies,19,19,5.8,3139998,138,28,6,11,3.0,5,0,Regularly busy,Most orders,Mid-range product,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,19,19,5.8,1977647,138,30,6,17,20.0,1,1,Regularly busy,Most orders,Mid-range product,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,19,19,5.8,389851,709,2,0,21,6.0,20,0,Busiest day,Average orders,Mid-range product,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,19,19,5.8,652770,764,1,3,13,7.0,10,0,Slowest day,Most orders,Mid-range product,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,19,19,5.8,1813452,764,3,4,17,9.0,11,1,Slowest day,Most orders,Mid-range product,3,New customer,4.972414

In [35]:
# create flag for low spender
ords_prods_merge.loc[ords_prods_merge['avg_spending'] < 10, 'spender_flag'] = 'Low spender'

In [37]:
# create flag for high spender
ords_prods_merge.loc[ords_prods_merge['avg_spending'] >= 10, 'spender_flag'] = 'High spender'

In [40]:
# checking for new columnns created: spender_flag and average price paid by each user_id
ords_prods_merge.head(50)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,days_since_prior_order,add_to_cart_order,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_spending,spender_flag
0,1,Chocolate Sandwich Cookies,19,19,5.8,3139998,138,28,6,11,3.0,5,0,Regularly busy,Most orders,Mid-range product,32,Regular customer,6.935811,Low spender
1,1,Chocolate Sandwich Cookies,19,19,5.8,1977647,138,30,6,17,20.0,1,1,Regularly busy,Most orders,Mid-range product,32,Regular customer,6.935811,Low spender
2,1,Chocolate Sandwich Cookies,19,19,5.8,389851,709,2,0,21,6.0,20,0,Busiest day,Average orders,Mid-range product,5,New customer,7.930208,Low spender
3,1,Chocolate Sandwich Cookies,19,19,5.8,652770,764,1,3,13,7.0,10,0,Slowest day,Most orders,Mid-range product,3,New customer,4.972414,Low spender
4,1,Chocolate Sandwich Cookies,19,19,5.8,1813452,764,3,4,17,9.0,11,1,Slowest day,Most orders,Mid-range product,3,New customer,4.972414,Low spender
5,1,Chocolate Sandwich Cookies,19,19,5.8,1701441,777,16,1,7,26.0,7,0,Busiest day,Average orders,Mid-range product,26,Regular customer,6.935398,Low spender
6,1,Chocolate Sandwich Cookies,19,19,5.8,1871483,825,3,2,14,30.0,2,0,Regularly busy,Most orders,Mid-range product,9,New customer,5.957576,Low spender
7,1,Chocolate Sandwich Cookies,19,19,5.8,1290456,910,12,3,10,30.0,1,0,Slowest day,Most orders,Mid-range product,12,Regular customer,6.680000,Low spender
8,1,Chocolate Sandwich Cookies,19,19,5.8,369558,1052,10,1,20,19.0,1,0,Busiest day,Average orders,Mid-range product,20,Regular customer,7.162500,Low spender
9,1,Chocolate Sandwich Cookies,19,19,5.8,589712,1052,15,1,12,15.0,2,1,Busiest day,Most orders,Mid-range product,20,Regular customer,7.162500,Low spender
10,1,Chocolate Sandwich Cookies,19,19,5.8,1798115,1379,1,5,11,7.0,1,0,Regularly busy,Most orders,Mid-range product,10,New customer,5.813636,Low spender
11,1,Chocolate Sandwich Cookies,19,19,5.8,497193,1480,36,3,13,7.0,1,0,Slowest day,Most orders,Mid-range product,43,Loyal customer,5.081633,Low spender
12,1,Chocolate Sandwich Cookies,19,19,5.8,1727826,1480,38,4,13,7.0,3,1,Slowest day,Most orders,Mid-range product,43,Loyal customer,5.081633,Low spender
13,1,Chocolate Sandwich Cookies,19,19,5.8,2694698,1480,39,2,12,12.0,4,1,Regularly busy,Most orders,Mid-range product,43,Loyal customer,5.081633,Low spender
14,1,Chocolate Sandwich Cookies,19,19,5.8,3171753,1494,6,3,10,2.0,8,0,Slowest day,Most orders,Mid-range product,13,Regular customer,6.803797,Low spender
15,1,Chocolate Sandwich Cookies,19,19,5.8,186761,1494,7,2,8,6.0,18,1,Regularly busy,Average orders,Mid-range product,13,Regular customer,6.803797,Low spender
16,1,Chocolate Sandwich Cookies,19,19,5.8,317121,1494,9,5,8,10.0,12,1,Regularly busy,Average orders,Mid-range product,13,Regular customer,6.803797,Low spender
17,1,Chocolate Sandwich Cookies,19,19,5.8,200390,1540,4,2,0,7.0,10,0,Regularly busy,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
18,1,Chocolate Sandwich Cookies,19,19,5.8,374436,1540,5,1,21,6.0,9,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
19,1,Chocolate Sandwich Cookies,19,19,5.8,2920553,1540,6,1,0,14.0,9,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
20,1,Chocolate Sandwich Cookies,19,19,5.8,2813049,1540,7,2,2,8.0,7,1,Regularly busy,Fewest orders,Mid-range product,28,Regular customer,6.607122,Low spender
21,1,Chocolate Sandwich Cookies,19,19,5.8,2365998,1540,8,1,23,6.0,6,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
22,1,Chocolate Sandwich Cookies,19,19,5.8,1604797,1540,9,1,3,28.0,6,1,Busiest day,Fewest orders,Mid-range product,28,Regular customer,6.607122,Low spender
23,1,Chocolate Sandwich Cookies,19,19,5.8,2799665,1540,14,1,14,7.0,10,1,Busiest day,Most orders,Mid-range product,28,Regular customer,6.607122,Low spender
24,1,Chocolate Sandwich Cookies,19,19,5.8,2228851,1540,15,1,14,7.0,3,1,Busiest day,Most orders,Mid-range product,28,Regular customer,6.607122,Low spender
25,1,Chocolate Sandwich Cookies,19,19,5.8,2337422,1540,18,0,21,0.0,5,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
26,1,Chocolate Sandwich Cookies,19,19,5.8,2699008,1540,19,0,22,7.0,11,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
27,1,Chocolate Sandwich Cookies,19,19,5.8,1914830,1540,20,0,22,7.0,11,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
28,1,Chocolate Sandwich Cookies,19,19,5.8,783503,1540,21,0,20,7.0,5,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
29,1,Chocolate Sandwich Cookies,19,19,5.8,2500516,1540,22,0,22,7.0,15,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
30,1,Chocolate Sandwich Cookies,19,19,5.8,716845,1540,24,4,22,3.0,4,1,Slowest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
31,1,Chocolate Sandwich Cookies,19,19,5.8,1955535,1540,25,6,19,16.0,6,1,Regularly busy,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
32,1,Chocolate Sandwich Cookies,19,19,5.8,1424793,1540,27,1,1,5.0,1,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
33,1,Chocolate Sandwich Cookies,19,19,5.8,749498,1540,28,0,21,6.0,1,1,Busiest day,Average orders,Mid-range product,28,Regular customer,6.607122,Low spender
34,1,Chocolate Sandwich Cookies,19,19,5.8,2434812,1598,1,2,12,7.0,2,0,Regularly busy,Most orders,Mid-range product,4,New customer,7.123529,Low spender
35,1,Chocolate Sandwich Cookies,19,19,5.8,1531889,1598,2,2,10,21.0,2,1,Regularly busy,Most orders,Mid-range product,4,New customer,7.123529,Low spender
36,1,Chocolate Sandwich Cookies,19,19,5.8,726947,1598,3,4,17,2.0,3,1,Slowest day,Most orders,Mid-range product,4,New customer,7.123529,Low spender
37,1,Chocolate Sandwich Cookies,19,19,5.8,627615,1647,1,1,9,7.0,1,0,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender
38,1,Chocolate Sandwich Cookies,19,19,5.8,2507439,1647,4,0,13,18.0,6,1,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender
39,1,Chocolate Sandwich Cookies,19,19,5.8,1152609,1647,6,1,9,8.0,3,1,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender
40,1,Chocolate Sandwich Cookies,19,19,5.8,1048339,1647,8,0,17,30.0,10,1,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender
41,1,Chocolate Sandwich Cookies,19,19,5.8,2818381,1647,9,4,15,25.0,1,1,Slowest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender
42,1,Chocolate Sandwich Cookies,19,19,5.8,2722928,2833,1,0,14,7.0,12,0,Busiest day,Most orders,Mid-range product,10,New customer,7.377143,Low spender
43,1,Chocolate Sandwich Cookies,19,19,5.8,1482338,2850,7,1,16,9.0,10,0,Busiest day,Most orders,Mid-range product,23,Regular customer,8.054153,Low spender
44,1,Chocolate Sandwich Cookies,19,19,5.8,2311344,2857,24,1,8,10.0,5,0,Busiest day,Average orders,Mid-range product,25,Regular customer,8.353793,Low spender
45,1,Chocolate Sandwich Cookies,19,19,5.8,812943,3010,5,3,10,7.0,11,0,Slowest day,Most orders,Mid-range product,13,Regular customer,6.452800,Low spender
46,1,Chocolate Sandwich Cookies,19,19,5.8,256839,3029,1,2,20,7.0,8,0,Regularly busy,Average orders,Mid-range product,5,New customer,7.960606,Low spender
47,1,Chocolate Sandwich Cookies,19,19,5.8,2192488,3395,4,2,10,30.0,7,0,Regularly busy,Most orders,Mid-range product,6,New customer,6.322222,Low spender
48,1,Chocolate Sandwich Cookies,19,19,5.8,207661,3904,1,1,14,7.0,2,0,Busiest day,Most orders,Mid-range product,3,New customer,7.511111,Low spender
49,1,Chocolate Sandwich Cookies,19,19,5.8,1394659,4006,2,1,10,7.0,8,0,Busiest day,Most orders,Mid-range product,42,Loyal customer,7.441100,Low spender

### Step 7

In [43]:
# adding a new column for the median number of days since last order for each user_id

ords_prods_merge['last_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [45]:
# checking  addition of the column for the median of days since prior order

ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 21 columns):
 #   Column                  Dtype
---  ------                  -----
 0   product_id              int32
 1   product_name            category
 2   aisle_id                int16
 3   department_id           int8
 4   prices                  float64
 5   order_id                int32
 6   user_id                 int32
 7   order_number            int8
 8   orders_day_of_week      int8
 9   hour_of_day_ordered     int8
 10  days_since_prior_order  float16
 11  add_to_cart_order       int16
 12  reordered               int8
 13  busiest_days            category
 14  busiest_period_of_day   category
 15  price_range_loc         category
 16  max_order               int8
 17  loyalty_flag            category
 18  avg_spending            float64
 19  spender_flag            object
 20  last_order              float16
dtypes: category(5), float16(2), float64(2), int16(2), int32(3), int8(6), object(1)
memory usage: 2.0+ GB

In [56]:
#  create flag for Non-frequent customer
ords_prods_merge.loc[ords_prods_merge['last_order'] > 20, 'ord_freq_flag'] = 'Non-frequent customer'

In [57]:
#  create flag for regular customer
ords_prods_merge.loc[(ords_prods_merge['last_order'] > 10) & (ords_prods_merge['last_order'] <=20), 'ord_freq_flag'] = 'regular customer'

In [58]:
# create flag for frequent customer
ords_prods_merge.loc[ords_prods_merge['last_order'] <= 10, 'ord_freq_flag'] = 'Frequent customer'

In [59]:
# checking the addition of the flag column.
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_spending,spender_flag,last_order,ord_freq_flag
0,1,Chocolate Sandwich Cookies,19,19,5.8,3139998,138,28,6,11,...,0,Regularly busy,Most orders,Mid-range product,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,19,19,5.8,1977647,138,30,6,17,...,1,Regularly busy,Most orders,Mid-range product,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,19,19,5.8,389851,709,2,0,21,...,0,Busiest day,Average orders,Mid-range product,5,New customer,7.930208,Low spender,7.0,Frequent customer
3,1,Chocolate Sandwich Cookies,19,19,5.8,652770,764,1,3,13,...,0,Slowest day,Most orders,Mid-range product,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,19,19,5.8,1813452,764,3,4,17,...,1,Slowest day,Most orders,Mid-range product,3,New customer,4.972414,Low spender,9.0,Frequent customer

In [60]:
# checking maximum days since last order
ords_prods_merge['last_order'].max()

30.0

In [62]:
# checking accuracy of the ord_freq flag. It works. Users with more than 20 days since last order are flagged as non-frequent customers 

ords_prods_merge[ords_prods_merge['ord_freq_flag'] =='Non-frequent customer'].head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_spending,spender_flag,last_order,ord_freq_flag
37,1,Chocolate Sandwich Cookies,19,19,5.8,627615,1647,1,1,9,...,0,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
38,1,Chocolate Sandwich Cookies,19,19,5.8,2507439,1647,4,0,13,...,1,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
39,1,Chocolate Sandwich Cookies,19,19,5.8,1152609,1647,6,1,9,...,1,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
40,1,Chocolate Sandwich Cookies,19,19,5.8,1048339,1647,8,0,17,...,1,Busiest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
41,1,Chocolate Sandwich Cookies,19,19,5.8,2818381,1647,9,4,15,...,1,Slowest day,Most orders,Mid-range product,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
46,1,Chocolate Sandwich Cookies,19,19,5.8,256839,3029,1,2,20,...,0,Regularly busy,Average orders,Mid-range product,5,New customer,7.960606,Low spender,28.0,Non-frequent customer
55,1,Chocolate Sandwich Cookies,19,19,5.8,2735922,4141,2,0,8,...,0,Busiest day,Average orders,Mid-range product,9,New customer,6.033333,Low spender,30.0,Non-frequent customer
57,1,Chocolate Sandwich Cookies,19,19,5.8,3185558,4553,3,5,16,...,0,Regularly busy,Most orders,Mid-range product,4,New customer,5.715789,Low spender,30.0,Non-frequent customer
59,1,Chocolate Sandwich Cookies,19,19,5.8,513100,6866,1,4,15,...,0,Slowest day,Most orders,Mid-range product,6,New customer,4.807143,Low spender,30.0,Non-frequent customer
71,1,Chocolate Sandwich Cookies,19,19,5.8,1486756,8735,8,4,11,...,0,Slowest day,Most orders,Mid-range product,9,New customer,5.850000,Low spender,24.0,Non-frequent customer

In [64]:
# Checking the accuracy of the spender flag. Yes, it looks like "high spenders" are associated with purchases of more than $10.

ords_prods_merge[ords_prods_merge['spender_flag'] == 'High spender'].head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_spending,spender_flag,last_order,ord_freq_flag
72,1,Chocolate Sandwich Cookies,19,19,5.8,632514,9293,2,0,12,...,0,Busiest day,Most orders,Mid-range product,5,New customer,11.857143,High spender,30.0,Non-frequent customer
73,1,Chocolate Sandwich Cookies,19,19,5.8,1253470,9293,3,3,13,...,1,Slowest day,Most orders,Mid-range product,5,New customer,11.857143,High spender,30.0,Non-frequent customer
88,1,Chocolate Sandwich Cookies,19,19,5.8,1526735,10315,1,0,16,...,0,Busiest day,Most orders,Mid-range product,5,New customer,10.188889,High spender,10.0,Frequent customer
335,1,Chocolate Sandwich Cookies,19,19,5.8,2268736,36564,3,3,13,...,0,Slowest day,Most orders,Mid-range product,3,New customer,11.233333,High spender,15.5,regular customer
368,1,Chocolate Sandwich Cookies,19,19,5.8,420339,43360,5,1,10,...,0,Busiest day,Most orders,Mid-range product,18,Regular customer,855.954140,High spender,8.0,Frequent customer
492,1,Chocolate Sandwich Cookies,19,19,5.8,1501823,54136,18,2,13,...,0,Regularly busy,Most orders,Mid-range product,23,Regular customer,98.685276,High spender,11.0,regular customer
776,1,Chocolate Sandwich Cookies,19,19,5.8,888423,86020,1,6,13,...,0,Regularly busy,Most orders,Mid-range product,42,Loyal customer,208.398651,High spender,7.0,Frequent customer
777,1,Chocolate Sandwich Cookies,19,19,5.8,1282518,86020,7,4,16,...,1,Slowest day,Most orders,Mid-range product,42,Loyal customer,208.398651,High spender,7.0,Frequent customer
778,1,Chocolate Sandwich Cookies,19,19,5.8,843117,86020,9,1,10,...,1,Busiest day,Most orders,Mid-range product,42,Loyal customer,208.398651,High spender,7.0,Frequent customer
810,1,Chocolate Sandwich Cookies,19,19,5.8,705930,89592,7,5,2,...,0,Regularly busy,Fewest orders,Mid-range product,50,Loyal customer,190.033439,High spender,5.0,Frequent customer

In [65]:
# Checking the accuracy of the spender flag. Yes it works. For avg spending > 10, the spender flag is high spender. 
ords_prods_merge[ords_prods_merge['avg_spending'] > 10 ].head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_day_ordered,...,reordered,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_spending,spender_flag,last_order,ord_freq_flag
72,1,Chocolate Sandwich Cookies,19,19,5.8,632514,9293,2,0,12,...,0,Busiest day,Most orders,Mid-range product,5,New customer,11.857143,High spender,30.0,Non-frequent customer
73,1,Chocolate Sandwich Cookies,19,19,5.8,1253470,9293,3,3,13,...,1,Slowest day,Most orders,Mid-range product,5,New customer,11.857143,High spender,30.0,Non-frequent customer
88,1,Chocolate Sandwich Cookies,19,19,5.8,1526735,10315,1,0,16,...,0,Busiest day,Most orders,Mid-range product,5,New customer,10.188889,High spender,10.0,Frequent customer
335,1,Chocolate Sandwich Cookies,19,19,5.8,2268736,36564,3,3,13,...,0,Slowest day,Most orders,Mid-range product,3,New customer,11.233333,High spender,15.5,regular customer
368,1,Chocolate Sandwich Cookies,19,19,5.8,420339,43360,5,1,10,...,0,Busiest day,Most orders,Mid-range product,18,Regular customer,855.954140,High spender,8.0,Frequent customer
492,1,Chocolate Sandwich Cookies,19,19,5.8,1501823,54136,18,2,13,...,0,Regularly busy,Most orders,Mid-range product,23,Regular customer,98.685276,High spender,11.0,regular customer
776,1,Chocolate Sandwich Cookies,19,19,5.8,888423,86020,1,6,13,...,0,Regularly busy,Most orders,Mid-range product,42,Loyal customer,208.398651,High spender,7.0,Frequent customer
777,1,Chocolate Sandwich Cookies,19,19,5.8,1282518,86020,7,4,16,...,1,Slowest day,Most orders,Mid-range product,42,Loyal customer,208.398651,High spender,7.0,Frequent customer
778,1,Chocolate Sandwich Cookies,19,19,5.8,843117,86020,9,1,10,...,1,Busiest day,Most orders,Mid-range product,42,Loyal customer,208.398651,High spender,7.0,Frequent customer
810,1,Chocolate Sandwich Cookies,19,19,5.8,705930,89592,7,5,2,...,0,Regularly busy,Fewest orders,Mid-range product,50,Loyal customer,190.033439,High spender,5.0,Frequent customer

In [66]:
# checking memory usage of the ords_prods_merge dataframe
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 22 columns):
 #   Column                  Dtype
---  ------                  -----
 0   product_id              int32
 1   product_name            category
 2   aisle_id                int16
 3   department_id           int8
 4   prices                  float64
 5   order_id                int32
 6   user_id                 int32
 7   order_number            int8
 8   orders_day_of_week      int8
 9   hour_of_day_ordered     int8
 10  days_since_prior_order  float16
 11  add_to_cart_order       int16
 12  reordered               int8
 13  busiest_days            category
 14  busiest_period_of_day   category
 15  price_range_loc         category
 16  max_order               int8
 17  loyalty_flag            category
 18  avg_spending            float64
 19  spender_flag            object
 20  last_order              float16
 21  ord_freq_flag           object
dtypes: category(5), float16(2), float64(2), int16(2), int32(3), int8(6), object(2)
memory usage: 2.2+ GB

In [67]:
# changing data types to reduce memory usage
ords_prods_merge['spender_flag'] = ords_prods_merge['spender_flag'].astype('category')
ords_prods_merge['ord_freq_flag'] = ords_prods_merge['ord_freq_flag'].astype('category')

In [68]:
# checking memory usage
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 22 columns):
 #   Column                  Dtype
---  ------                  -----
 0   product_id              int32
 1   product_name            category
 2   aisle_id                int16
 3   department_id           int8
 4   prices                  float64
 5   order_id                int32
 6   user_id                 int32
 7   order_number            int8
 8   orders_day_of_week      int8
 9   hour_of_day_ordered     int8
 10  days_since_prior_order  float16
 11  add_to_cart_order       int16
 12  reordered               int8
 13  busiest_days            category
 14  busiest_period_of_day   category
 15  price_range_loc         category
 16  max_order               int8
 17  loyalty_flag            category
 18  avg_spending            float64
 19  spender_flag            category
 20  last_order              float16
 21  ord_freq_flag           category
dtypes: category(7), float16(2), float64(2), int16(2), int32(3), int8(6)
memory usage: 1.8 GB

In [70]:
path = r"C:\Users\Windows\Instacart Basket Analysis"

In [72]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge2.pkl'))